### ISSUE TITLE
Add Bordeaux, France (via adding fr-sw of navitia API)

### ISSUE THREAD

**Issue by kalon33** [grote/Transportr#137]
Hi, Could you please add fr-sw navitia API region to your app?

A betatest of the app using the new Navitia API without region splitting would also be awesome to be able to plan correctly trips with intercity trains (cf Navitia team email from a few days ago)

Thanks for looking at this!

**Comment by grote** [comment]
Adding fr-sw should be very easy.

Regarding the world region, is that already available? I only remember a statement saying: "we currently work on"

**Comment by grote** [comment]
Look at [SpainProvider.java](/grote/Transportr/blob/master/src/de/schildbach/pte/SpainProvider.java) for an example of how fr-sw could be added easily.

**Comment by kalon33** [comment]
@grote I just contributed the relevant changes in a PR for upstream public-transport-enabler project: https://github.com/schildbach/public-transport-enabler/pull/55

**Comment by grote** [comment]
Wow that was very fast! As soon as it is merged into the PTE, I will update and include it in Transportr.

**Comment by kalon33** [comment]
@grote yes it was very fast but unfortunately the PR is not integrated yet. Reviews are pretty positive but it has not yet been pulled. It's a shame as I will travel to Bordeaux next week and the week after...

**Comment by grote** [comment]
That's too bad :(
What you could do is to build Transportr yourself from source and already add fr-sw like I added the SpainProvider. Then you can give your provider an actual test run before it is merged.

**Comment by kalon33** [comment]
@grote commits were merged, so you can update and include it. Thanks for your help :)

**Comment by grote** [comment]
Awesome! Thanks for **your** work!

Do you have a logo for that network as well? See [Transport Network Logos](https://transportr.grobox.de/#contribute) for more information on those.

**Comment by grote** [comment]
I am getting this when searching Barriere De Paris to Bardanac:
```
java.lang.IllegalArgumentException: Unhandled product: SUBWAY
     at de.schildbach.pte.FrenchSouthWestProvider.getLineStyle(FrenchSouthWestProvider.java:65)
```

**Comment by kalon33** [comment]
@grote there's multiple logos as there are multiple networks there. 

For the Unhandled product error, I just forgot that fr-sw also covers Toulouse, which is the only town to have a subway in the south west of France. Just working on a PR to fix this before sleeping.

**Comment by grote** [comment]
> there's multiple logos as there are multiple networks there.

I know it is difficult, but some logo is better than none. Maybe there's a logo for the region rather than a single transport company? Or one company is especially prominent in the region?

> For the Unhandled product error, I just forgot that fr-sw also covers Toulouse, which is the only town 
> to have a subway in the south west of France. Just working on a PR to fix this before sleeping.

Awesome! So I was lucky with testing a good connection ;)

I added the broken provider already in 25a5143, btw.

**Comment by kalon33** [comment]
@grote the region covered by fr-sw is currently two french administrative regions (the subdivision like länders in Germany), so that's not simpler... the two main local networks covered currently are TBC (http://www.infotbc.com) and Tisseo (http://www.tisseo.fr/) which are in each of the two main towns of these different regions.

Bug fixed in https://github.com/schildbach/public-transport-enabler/issues/60 :)

**Comment by kalon33** [comment]
@grote "SUBWAY" bug is now fixed upstream. I'm currently have a look at the code to see if I can find where the problem linked to Navitia API is.

**Comment by grote** [comment]
Would be great if you could find the problem, because I am reluctant to make a new release with new providers that don't fully work.

**Comment by kalon33** [comment]
@grote I just made a PR https://github.com/schildbach/public-transport-enabler/pull/61 that should hopefully fix that problem. I couldn't properly test it as I ran into some troubles on my laptop, and hadn't my desktop machine to test, but I tested manually some requests to the Navitia API that worked using my changes.

**Comment by kalon33** [comment]
@grote problem is fixed upstream!

**Comment by grote** [comment]
Great! Any idea for the graphic?

**Comment by grote** [comment]
Looking for nearby stations does not show an exception anymore, but I am only finding the station I looked for, not others. So this is not completely fixed :(

**Comment by kalon33** [comment]
This may be linked to the variables passed to the request to the API, that define the radius in m around the stop to find stops, the number of stops and the depth of the request.

I don't know (yet?) Where they are set, especially if you have to set them in your app. Setting arbitrary values properly return multiple stops when they are "normal" (1000m, 20stops), but still, I don't know where the variables that set these values in the request are set.


----- Mail d'origine -----
De: Torsten Grote <notifications@github.com>
À: grote/Transportr <Transportr@noreply.github.com>
Cc: Nicolas Derive <kalon33@ubuntu.com>
Envoyé: Mon, 21 Dec 2015 19:24:57 +0100 (CET)
Objet: Re: [Transportr] Add Bordeaux, France (via adding fr-sw of navitia API) (#137)

Looking for nearby stations does not show an exception anymore, but I am only finding the station I looked for, not others. So this is not completely fixed :(

---

**Comment by grote** [comment]
Support for fr-sw is now available in the latest 1.0.2 release. I hope you had a self-compiled version with you for your trip. Thanks a lot for your help! :)

If you want to add further areas, that would be greatly appreciated!

PS. The nearby stations issue is still not fix. I will look into this soon.
